repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks: [id: black]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks: [id: isort]
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks: [id: flake8]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks: [id: mypy]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks: [id: detect-secrets]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.87.0            # latest release as of July 2025
    hooks:
      - id: terraform_fmt
        args: ["-recursive", "infra"]
      - id: terraform_tflint
        args: ["--recursive", "infra"]
      - id: terraform_trivy
        args: ["infra"]



