name: CI

on:
  push:
    branches: [main]        # run on direct pushes
  pull_request:             # and on every PR targeting main
    branches: [main]

jobs:
  test:
    name: Python ${{ matrix.python-version }} • ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11" ]
        os: [ ubuntu-latest ]          # keep single OS now; easy to add mac/win later

    steps:
      # 1 — Checkout code
      - uses: actions/checkout@v4

      # 2 — Python toolchain (matrix)
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      # 3 — Install Poetry **and** project deps in ONE step
      - name: Install Poetry + deps
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"        # make poetry visible to later steps
          poetry --version                                 # sanity print
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --no-root --with dev

      # 4 — Lint ✨
      - name: Run pre-commit hooks
        run: poetry run pre-commit run --all-files --show-diff-on-failure

      # 5 — Tests
      - name: Run pytest
        run: poetry run pytest -q

      # 6 — Static typing
      - name: Run mypy
        run: poetry run mypy src

      # 7 — Type check (mypy)  – keep after tests so type errors fail job even if tests pass
      - name: Static type check
        run: poetry run mypy src

